const title = "PROJECT";
console.log(typeof title);
const screens = "Простые, Сложные, Интерактивные";
console.log(screens);
const screenPrice = 1613;
console.log(screenPrice);
const rollback = 14;
console.log(rollback);
const fullPrice = 100000;
console.log(typeof fullPrice);
const adaptive = true;
console.log(typeof adaptive);
